### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by T-Clarkson** [T-Clarkson/BIOL3207_workshop#1]
- [ ] Add 'OA_bootstrapping_script.R' https://github.com/T-Clarkson/BIOL3207_workshop/labels/Hanee

- [ ] Conduct bootstrap analysis of data (resampling) https://github.com/T-Clarkson/BIOL3207_workshop/labels/Tianna

- [ ] Search literature for more applicable data https://github.com/T-Clarkson/BIOL3207_workshop/labels/Tianna
